import {
  Patient,
  PatientListItem,
  PatientDetail,
  AdminROIResponse,
  AuditLog,
} from "./types";

export const MOCK_PATIENTS: Patient[] = [
  {
    id: "p1",
    name: "Ramesh K.",
    age: 62,
    language: "Hindi",
    conditions: ["Type 2 Diabetes", "Hypertension"],
    doctor_id: "doc1",
    family_id: "fam1",
    created_at: "2026-09-20T10:00:00Z",
  },
  {
    id: "p2",
    name: "Anita S.",
    age: 54,
    language: "Kannada",
    conditions: ["Hypertension"],
    doctor_id: "doc1",
    family_id: "fam2",
    created_at: "2026-09-21T11:00:00Z",
  },
  {
    id: "p3",
    name: "Suresh P.",
    age: 48,
    language: "English",
    conditions: ["Type 2 Diabetes"],
    doctor_id: "doc1",
    family_id: "fam3",
    created_at: "2026-09-22T09:30:00Z",
  },
];

export const MOCK_PATIENT_LIST: PatientListItem[] = [
  {
    id: "p1",
    name: "Ramesh K.",
    age: 62,
    score: 75,
    band: "red",
    topReason: "Consecutive missed morning Metformin & BP spike (+14%)",
    lastSeen: "10 mins ago",
    conditions: ["Type 2 Diabetes", "Hypertension"],
  },
  {
    id: "p2",
    name: "Anita S.",
    age: 54,
    score: 52,
    band: "yellow",
    topReason: "Diastolic BP fluctuating (avg 88 mmHg)",
    lastSeen: "2 hours ago",
    conditions: ["Hypertension"],
  },
  {
    id: "p3",
    name: "Suresh P.",
    age: 48,
    score: 22,
    band: "green",
    topReason: "100% adherence, daily walking target met",
    lastSeen: "Yesterday",
    conditions: ["Type 2 Diabetes"],
  },
];

export const MOCK_PATIENT_DETAILS: Record<string, PatientDetail> = {
  p1: {
    profile: MOCK_PATIENTS[0],
    risk: {
      score: 75,
      band: "red",
      reasons: [
        {
          rule_id: "MED_MISSED_STREAK",
          text: "Missed 2 consecutive doses of Metformin 500mg",
          weight: 15,
        },
        {
          rule_id: "BP_TREND_UP",
          text: "Systolic BP up 14% vs previous 7-day average",
          weight: 20,
        },
        {
          rule_id: "BP_HIGH_ABS",
          text: "Latest systolic BP reading is 154/94 mmHg (elevated threshold)",
          weight: 20,
        },
        {
          rule_id: "STEPS_DROP",
          text: "Daily steps decreased by 46% (from 5,200 to 2,800)",
          weight: 10,
        },
        {
          rule_id: "RECENT_DISCHARGE",
          text: "Post-discharge observation window (discharged 8 days ago)",
          weight: 10,
        },
      ],
    },
    vitals: [
      { id: "v1", patient_id: "p1", type: "bp", value_a: 130, value_b: 82, recorded_at: "Day 1" },
      { id: "v2", patient_id: "p1", type: "bp", value_a: 132, value_b: 84, recorded_at: "Day 2" },
      { id: "v3", patient_id: "p1", type: "bp", value_a: 128, value_b: 80, recorded_at: "Day 3" },
      { id: "v4", patient_id: "p1", type: "bp", value_a: 135, value_b: 85, recorded_at: "Day 4" },
      { id: "v5", patient_id: "p1", type: "bp", value_a: 142, value_b: 88, recorded_at: "Day 5" },
      { id: "v6", patient_id: "p1", type: "bp", value_a: 148, value_b: 90, recorded_at: "Day 6" },
      { id: "v7", patient_id: "p1", type: "bp", value_a: 154, value_b: 94, recorded_at: "Day 7 (Today)" },
      { id: "v8", patient_id: "p1", type: "steps", value_a: 5400, value_b: null, recorded_at: "Day 1" },
      { id: "v9", patient_id: "p1", type: "steps", value_a: 5100, value_b: null, recorded_at: "Day 2" },
      { id: "v10", patient_id: "p1", type: "steps", value_a: 4900, value_b: null, recorded_at: "Day 3" },
      { id: "v11", patient_id: "p1", type: "steps", value_a: 4200, value_b: null, recorded_at: "Day 4" },
      { id: "v12", patient_id: "p1", type: "steps", value_a: 3600, value_b: null, recorded_at: "Day 5" },
      { id: "v13", patient_id: "p1", type: "steps", value_a: 3100, value_b: null, recorded_at: "Day 6" },
      { id: "v14", patient_id: "p1", type: "steps", value_a: 2800, value_b: null, recorded_at: "Day 7 (Today)" },
    ],
    medLogs: [
      {
        id: "m1",
        patient_id: "p1",
        medicine_id: "med1",
        medicine_name: "Metformin 500mg",
        dose: "1 tablet (Morning)",
        scheduled_at: "Today, 08:00 AM",
        taken_at: null,
        status: "missed",
      },
      {
        id: "m2",
        patient_id: "p1",
        medicine_id: "med2",
        medicine_name: "Amlodipine 5mg",
        dose: "1 tablet (Morning)",
        scheduled_at: "Today, 08:00 AM",
        taken_at: null,
        status: "missed",
      },
      {
        id: "m3",
        patient_id: "p1",
        medicine_id: "med1",
        medicine_name: "Metformin 500mg",
        dose: "1 tablet (Evening)",
        scheduled_at: "Yesterday, 08:00 PM",
        taken_at: "Yesterday, 08:15 PM",
        status: "taken",
      },
      {
        id: "m4",
        patient_id: "p1",
        medicine_id: "med1",
        medicine_name: "Metformin 500mg",
        dose: "1 tablet (Morning)",
        scheduled_at: "Yesterday, 08:00 AM",
        taken_at: null,
        status: "missed",
      },
      {
        id: "m5",
        patient_id: "p1",
        medicine_id: "med2",
        medicine_name: "Amlodipine 5mg",
        dose: "1 tablet (Morning)",
        scheduled_at: "Yesterday, 08:00 AM",
        taken_at: "Yesterday, 08:30 AM",
        status: "taken",
      },
    ],
    alerts: [
      {
        id: "a1",
        patient_id: "p1",
        level: "doctor",
        audience: "doctor",
        message: "URGENT: Ramesh K. flagged RED. Risk score jumped to 75 due to missed dose streak and BP spike.",
        created_at: "15 minutes ago",
        acknowledged_at: null,
      },
      {
        id: "a2",
        patient_id: "p1",
        level: "family",
        audience: "family",
        message: "Family ping sent to Karan: Ramesh ji has not taken morning Metformin.",
        created_at: "1 hour ago",
        acknowledged_at: "45 minutes ago",
      },
      {
        id: "a3",
        patient_id: "p1",
        level: "reminder",
        audience: "patient",
        message: "Automated reminder sent to Ramesh ji's phone for morning dose.",
        created_at: "2 hours ago",
        acknowledged_at: null,
      },
    ],
    consents: [
      { patient_id: "p1", category: "vitals", granted: true, updated_at: "2026-09-20" },
      { patient_id: "p1", category: "medicines", granted: true, updated_at: "2026-09-20" },
      { patient_id: "p1", category: "steps", granted: true, updated_at: "2026-09-20" },
      { patient_id: "p1", category: "glucose", granted: false, updated_at: "2026-09-20" },
    ],
  },
  p2: {
    profile: MOCK_PATIENTS[1],
    risk: {
      score: 52,
      band: "yellow",
      reasons: [
        {
          rule_id: "BP_TREND_UP",
          text: "Diastolic BP fluctuating upwards over 5 days",
          weight: 20,
        },
        {
          rule_id: "MED_ADHERENCE_LOW",
          text: "Adherence at 78% over the past 7 days",
          weight: 25,
        },
      ],
    },
    vitals: [
      { id: "v20", patient_id: "p2", type: "bp", value_a: 135, value_b: 85, recorded_at: "Day 1" },
      { id: "v21", patient_id: "p2", type: "bp", value_a: 136, value_b: 86, recorded_at: "Day 2" },
      { id: "v22", patient_id: "p2", type: "bp", value_a: 138, value_b: 87, recorded_at: "Day 3" },
      { id: "v23", patient_id: "p2", type: "bp", value_a: 140, value_b: 89, recorded_at: "Day 4" },
      { id: "v24", patient_id: "p2", type: "bp", value_a: 139, value_b: 88, recorded_at: "Day 5" },
      { id: "v25", patient_id: "p2", type: "steps", value_a: 4200, value_b: null, recorded_at: "Day 1" },
      { id: "v26", patient_id: "p2", type: "steps", value_a: 4100, value_b: null, recorded_at: "Day 2" },
      { id: "v27", patient_id: "p2", type: "steps", value_a: 4000, value_b: null, recorded_at: "Day 3" },
    ],
    medLogs: [
      {
        id: "m20",
        patient_id: "p2",
        medicine_id: "med3",
        medicine_name: "Telmisartan 40mg",
        dose: "1 tablet (Morning)",
        scheduled_at: "Today, 09:00 AM",
        taken_at: "Today, 09:10 AM",
        status: "taken",
      },
    ],
    alerts: [
      {
        id: "a20",
        patient_id: "p2",
        level: "reminder",
        audience: "patient",
        message: "Daily BP check reminder sent.",
        created_at: "3 hours ago",
        acknowledged_at: "2 hours ago",
      },
    ],
    consents: [
      { patient_id: "p2", category: "vitals", granted: true, updated_at: "2026-09-21" },
      { patient_id: "p2", category: "medicines", granted: true, updated_at: "2026-09-21" },
      { patient_id: "p2", category: "steps", granted: true, updated_at: "2026-09-21" },
      { patient_id: "p2", category: "glucose", granted: true, updated_at: "2026-09-21" },
    ],
  },
  p3: {
    profile: MOCK_PATIENTS[2],
    risk: {
      score: 22,
      band: "green",
      reasons: [],
    },
    vitals: [
      { id: "v30", patient_id: "p3", type: "bp", value_a: 120, value_b: 78, recorded_at: "Day 1" },
      { id: "v31", patient_id: "p3", type: "bp", value_a: 122, value_b: 80, recorded_at: "Day 2" },
      { id: "v32", patient_id: "p3", type: "bp", value_a: 118, value_b: 76, recorded_at: "Day 3" },
      { id: "v33", patient_id: "p3", type: "steps", value_a: 7500, value_b: null, recorded_at: "Day 1" },
      { id: "v34", patient_id: "p3", type: "steps", value_a: 8200, value_b: null, recorded_at: "Day 2" },
      { id: "v35", patient_id: "p3", type: "steps", value_a: 7900, value_b: null, recorded_at: "Day 3" },
    ],
    medLogs: [
      {
        id: "m30",
        patient_id: "p3",
        medicine_id: "med4",
        medicine_name: "Metformin 500mg",
        dose: "1 tablet (Morning)",
        scheduled_at: "Today, 08:00 AM",
        taken_at: "Today, 08:05 AM",
        status: "taken",
      },
    ],
    alerts: [],
    consents: [
      { patient_id: "p3", category: "vitals", granted: true, updated_at: "2026-09-22" },
      { patient_id: "p3", category: "medicines", granted: true, updated_at: "2026-09-22" },
      { patient_id: "p3", category: "steps", granted: false, updated_at: "2026-09-22" },
      { patient_id: "p3", category: "glucose", granted: true, updated_at: "2026-09-22" },
    ],
  },
};

export const MOCK_AUDIT_LOGS: AuditLog[] = [
  {
    id: "aud1",
    patient_id: "p1",
    actor_type: "doctor",
    actor_id: "doc1",
    actor: "Dr. Meera Rao",
    action: "Reviewed clinical telemetric history",
    category: "vitals",
    at: "10 mins ago",
  },
  {
    id: "aud2",
    patient_id: "p1",
    actor_type: "doctor",
    actor_id: "doc1",
    actor: "Dr. Meera Rao",
    action: "Requested pre-consult AI brief",
    category: "clinical_brief",
    at: "12 mins ago",
  },
  {
    id: "aud3",
    patient_id: "p1",
    actor_type: "system",
    actor_id: "risk_engine",
    actor: "Automated Escalation Rule",
    action: "Recomputed risk band to RED",
    category: "risk_evaluation",
    at: "15 mins ago",
  },
  {
    id: "aud4",
    patient_id: "p1",
    actor_type: "doctor",
    actor_id: "doc1",
    actor: "Dr. Meera Rao",
    action: "Viewed 14-day medication adherence logs",
    category: "medicines",
    at: "Yesterday, 04:30 PM",
  },
];

export const MOCK_ADMIN_ROI: AdminROIResponse = {
  readmissionsPrevented: 14,
  doctorHoursSaved: 38.5,
  alertsActioned: 126,
  patientsMonitored: 42,
  assumptions: [
    "Readmission prevention estimated at 1 averted admission per 9 high-risk alerts actioned within 3 hours.",
    "Doctor hours saved calculated as 18 minutes saved per prioritized consult via AI brief and structured telemetry.",
    "Cost of average hospital readmission in urban private centers estimated at ₹45,000.",
    "Adherence improvement baseline: +22% lift observed among patients with active family notifications.",
  ],
  alertsPerDay: [
    { date: "Oct 1", count: 14 },
    { date: "Oct 2", count: 19 },
    { date: "Oct 3", count: 16 },
    { date: "Oct 4", count: 22 },
    { date: "Oct 5", count: 28 },
  ],
};
